data_transformation_dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: database
      port: 5432
      user: postgres
      password: postgres
      dbname: stocks_db
      schema: public
      threads: 4