#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE stocks_db;
    GRANT ALL PRIVILEGES ON DATABASE stocks_db TO $POSTGRES_USER;
    CREATE DATABASE metabase_db;
    GRANT ALL PRIVILEGES ON DATABASE metabase_db TO $POSTGRES_USER;
EOSQL
